config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'books#index'
  resources :books
  resources :authors
  resources :reviews
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  attr_accessor :checkbox

  has_many :author_books
  has_many :books, through: :author_books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  attr_accessor :checkbox

  belongs_to :user

  has_many :book_genres
  has_many :genres, through: :book_genres

  has_many :author_books
  has_many :authors, through: :author_books

  has_many :book_images
  accepts_nested_attributes_for :book_images

  has_many :reviews

  def update_rating
    self.rating =  self.reviews.average(:rate)
    self.save
  end

  def author_rating
    self.reviews.where(user: self.user).first.rate unless self.reviews.where(user: self.user).blank?
  end

  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      where('name LIKE ?', "%#{pattern}%")
    end
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres
  has_many :books, through: :book_genres

  GENRE_SAMPLE = %w(Satire Health Guide Travel Science )
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :rate, presence: true, inclusion: { in: 1..5 }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :reviews

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if params[:agree].blank?
      redirect_back(fallback_location: root_path, notice: 'You must be agree.')
    elsif @author.save
      redirect_to root_path, notice: 'Author was created.'
    else
      redirect_to root_path, notice: 'Something wrong.'
    end
  end

  private

  def author_params
    params.require(:author).permit(:name_surname)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = case params[:sort]
              when 'All'
                Book.all
               when 'Satire'
                 Genre.where(title: 'Satire').first.books
              when 'Health'
                Genre.where(title: 'Health').first.books
              when 'Guide'
                Genre.where(title: 'Guide').first.books
              when 'Travel'
                Genre.where(title: 'Travel').first.books
              when 'Science'
                Genre.where(title: 'Science').first.books
              else
                Book.all
            end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @book_images = @book.book_images.build
  end

  def create
    @user = current_user
    @book = @user.books.new(book_params)

    if params[:agree].blank?
      redirect_back(fallback_location: root_path, notice: 'You must be agree.')
    elsif @book.save
      params[:book][:genres].each do |genre|
        BookGenre.create(book: @book, genre_id: genre.to_i) unless genre.blank?
      end

      params[:book][:authors].each do |author|
        AuthorBook.create(book: @book, author_id: author.to_i) unless author.blank?
      end

      params[:book][:image].each do |image|
        @book_images = @book.book_images.create!(image: image)
      end

      redirect_to root_path, notice: 'Book was created, but the book needs approval.'
    else
      redirect_to root_path, notice: 'Something wrong.'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, book_attachments_attributes: [:id, :book_id, :image])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @review = current_user.reviews.new(review_params)
    @book = Book.find(params[:review][:book_id])

    if @review.save
      @book.update_rating
      redirect_back(fallback_location: root_path, notice: 'Review was created.')
    else
      redirect_back(fallback_location: root_path, notice: 'Something wrong.')
    end
  end

  def destroy
    @review = Review.find(params[:id])

    if @review.user == current_user
      @review.destroy
      flash[:notice] = "Post was destroyed."
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "No access."
      redirect_back(fallback_location: root_path)
    end
  end

  def review_params
    params.require(:review).permit(:comment, :rate, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for(@author, html: {class: 'form-horizontal'}) do |f| %>
    <%= f.input :name_surname %>

    <p>I agree with the terms of the privacy policy and allow my personal data to be legitimately used.</p>

    <%= f.input :checkbox, label: 'I understand' do %>
        <%= check_box_tag :agree %>
    <% end %>


    <%= f.button :submit %>
<% end %>

app/views/authors/new.html.erb
<h2>Add new author</h2>
<%= render 'form' %>

app/views/books/_book.html.erb
<div class="well col-md-6">
  <div class="media">
    <a class="pull-left" href="#">
      <% if book.book_images.blank? %>
          <img class="media-object" src="http://placekitten.com/150/150">
      <% else %>
          <%= (image_tag(book.book_images.first.image.url(:main), size: "150")) %>
      <% end %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to book.title, book_path(book) %></h4>
      <p class="text-right">By <%= book.user.name + ' ' + book.user.surname %></p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
        Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
        dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
        Aliquam in felis sit amet augue.</p>
      <ul class="list-inline list-unstyled">
        <li><span><i class="glyphicon glyphicon-calendar"></i> <%= time_ago_in_words(book.created_at) %> ago </span></li>
        <li>|</li>
        <span><i class="glyphicon glyphicon-comment"></i> <%= book.reviews.count %> comments</span>
        <li>|</li>
        <li>
          <% 5.times do |i| %>
              <% if book.rating > i %>
                  <span class="glyphicon glyphicon-star"></span>
              <% else %>
                  <span class="glyphicon glyphicon-star-empty"></span>
              <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :genres, collection: Genre.all, input_html: { class: 'multiselectuser', multiple: true} %>
    <%= f.input :authors, collection: Author.all, label_method: :name_surname, value_method: :id, input_html: { class: 'multiselectuser', multiple: true} %>

    <%= f.input :image, as: :file, input_html: { :multiple => true }, name: "book[book_attachments_attributes][][image]" %>
    <p>I agree with the terms of the privacy policy and allow my personal data to be legitimately used.</p>

    <%= f.input :checkbox, label: 'I understand' do %>
        <%= check_box_tag :agree %>
    <% end %>


    <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<div class="container">

  <h2>All books</h2>

  <div>
    <%= link_to 'All', books_path(:sort => 'All'), class: 'btn btn-default btn-sm' %>
    <%= link_to 'Satire', books_path(:sort => 'Satire'), class: 'btn btn-default btn-sm' %>
    <%= link_to 'Health', books_path(:sort => 'Health'), class: 'btn btn-default btn-sm' %>
    <%= link_to 'Guide', books_path(:sort => 'Guide'), class: 'btn btn-default btn-sm' %>
    <%= link_to 'Travel', books_path(:sort => 'Travel'), class: 'btn btn-default btn-sm' %>
    <%= link_to 'Science', books_path(:sort => 'Science'), class: 'btn btn-default btn-sm' %>
  </div>
  <hr>

  <%= content_tag(:h1, 'There will be books soon!') if @books.blank? %>

  <%= render @books %>

</div>

app/views/books/new.html.erb
<h2>Add new book</h2>
<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
  <h2><%= @book.title %></h2>
  <hr>
  <div class="col-md-3">
    <h4>Book image</h4>
    <%= image_tag @book.book_images.first.image.url(:title) unless @book.book_images.blank? %>
  </div>
  <div class="col-md-9">
    <h4>Description</h4>

    <%= @book.description %>
    <hr>
    <% @book.book_images.each do |book_image| %>
      <%= image_tag book_image.image.url(:main) %>
    <% end %>
  </div>
  <div class="col-md-12">
    <hr>
    <h4>Information</h4>
    <p><strong>Author:</strong> <%= @book.authors.map {|author| author.name_surname }.join(', ') %><p>
    <p><strong>Category:</strong> <%= @book.genres.map {|genre| genre.title }.join(', ') %><p>
    <p><strong>Book rating:</strong> <%= @book.rating.to_f.round(1) %> <p>
    <p><strong>Author rating:</strong> <%= @book.author_rating.round(1) unless @book.author_rating.blank? %> <p>
    <p><strong>Added by:</strong> <%= @book.user.name + ' ' + @book.user.surname %>, on <%= @book.created_at.to_date %> <p>
  </div>
  <div class="col-md-12">
    <hr>
    <h4>Reviews</h4>
    <%= render @book.reviews %>

    <%= render 'reviews/form' unless @book.reviews.exists?(user: current_user) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LastCw</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">

    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to '#' %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to 'Add new book', new_book_path %></li>
          <li><%= link_to 'Add new author', new_author_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Edit registration', edit_user_password_path) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="container">
  <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>
</div>


</body>
</html>

app/views/reviews/_form.html.erb
<% @review ||= Review.new %>

<%= simple_form_for(@review, html: {class: 'form-horizontal'}) do |f| %>
    <%= f.input :comment %>

    <strong class="pull-left">Bad</strong><strong class="pull-right">Great</strong>
    <%= f.range_field :rate, :in => 1..5, :step => '1' %>


    <%= f.hidden_field :book_id, value: @book.id %>

    <%= f.button :submit %>
<% end %>

app/views/reviews/_review.html.erb
<div class="">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong><%= review.user.name + ' ' + review.user.surname %></strong>
      <span class="text-muted">commented <%= time_ago_in_words(review.created_at) %> ago</span>
    </div>
    <div class="panel-body">
      <h4><%= review.comment %></h4>
      <% 5.times do |i| %>
          <% if review.rate > i %>
              <span class="glyphicon glyphicon-star"></span>
          <% else %>
              <span class="glyphicon glyphicon-star-empty"></span>
          <% end %>
      <% end %>
    </div><!-- /panel-body -->
    <%= link_to 'Delete', review_path(review), method: :delete if review.user == current_user %>
  </div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->